### ISSUE TITLE
一个Python小白来自灵魂深处的疑问

### ISSUE THREAD

**Issue by a844672236** [skyduy/doudizhu-rl#1]
envi.py里边的
    import r
    from env import Env as CEnv

这两个都是啥?我安装了env模块和pipenv模块  表示都找不到Env这个东西

还有r是啥???   

我表示我快懵逼了...

**Comment by skyduy** [comment]
一阵见血的两个问题，
r在：https://github.com/deecamp2019-group20/bottleneck/tree/master/get_moves
env在：https://github.com/deecamp2019-group20/Baseline-RHCP

这个涉及pybind11的pre知识。

**Comment by a844672236** [comment]
o((⊙﹏⊙))o  多谢大佬 ,   我表示我是写android的,最近公司没项目,想研究研究机器学习, 结果发现没有java平台(语言)的教程,...  心塞...
